### ISSUE TITLE
Breaks uk.webuy.com

### ISSUE THREAD

**Issue by cxw42** [gregsadetsky/chrome-dont-add-custom-search-engines#12]
Reported by [Dan Reeves](https://plus.google.com/114088808989216500350) via web store 2018/04/08.

When the extension is not loaded:

![screenshot](https://user-images.githubusercontent.com/10515894/39764276-48258adc-52ad-11e8-89ab-ffe59f77f8b2.png)

When the extension is loaded:

![image](https://user-images.githubusercontent.com/10515894/39764307-5a7504ec-52ad-11e8-9818-dd6d7b6aa91d.png)

**Comment by Procyon-b** [comment]
I have tested with this particular page, and I think we want the part 'spoilFormGet' to be start _after_ body.onload. I don't know what the scripts on this page do, but the form completely disappears. document.forms.length is equal to 0 after the "fix"

In main(), enclose the
document.querySelectorAll('form:-webkit-any(...
if(DEBUG) {...
}

inside a:
window.addEventListener('load', function(){
[paste old code here]
} );

And all is good afterwards

**Comment by cxw42** [comment]
@Procyon-b thanks very much for the fix!  Would you be willing to submit a pull request so your name will be in the commit history?  Either way, I'll try it out and see if I have the same results.

**Comment by Procyon-b** [comment]
You'll have to tell me how to do it. I'm new here. I have created an account just for this.  :)
I haven't looked around yet.

**Comment by Procyon-b** [comment]
I'm not using a client yet. Just the web interface.
I don't have the time right now, but I'll look at it.

**Comment by cxw42** [comment]
OK - no worries!  Here's the [doc](https://help.github.com/desktop/guides/contributing-to-projects/creating-a-pull-request/) for using GitHub desktop.  If I get to it first, I'll let you know :) .  Last thing for today --- would you be willing to attach your edited source file to this thread?  That way I can test exactly what you are using.

**Comment by Procyon-b** [comment]
[content.zip](https://github.com/gregsadetsky/chrome-dont-add-custom-search-engines/files/2085056/content.zip)

Sorry for the delay, I'm back now.
Here is a copy of a modified content.js

**Comment by cxw42** [comment]
@Procyon-b Didn't notice the delay - I was working on my day job ;) .  Received with thanks!  I'll try it out.

**Comment by Procyon-b** [comment]
I have made some tests, And I think we can add a test to only do "spoilFormGet" when current page's pathname is '/'.
From what I read on https://www.chromium.org/tab-to-search and tests, I can tell you that chrome follows rules of point 2, except for the case when there is an onsubmit script.
If we have a list of test pages we can foolproof this assertion.

**Comment by Procyon-b** [comment]
Any activity ?
Have you seen my pull request. Have I done it correctly ?
I have been running that version of content.js , and so far no custom search added.

**Comment by cxw42** [comment]
:) Been buried at work - I'm sorry to say I haven't had a chance.  Will as soon as I can, though!  I certainly don't want to leave you hanging.  Thanks for your patience!

**Comment by Procyon-b** [comment]
No need to be sorry. I wasn't certain it was done correctly.
That's all.   :)
