### ISSUE TITLE
duckduckgo.com is getting through

### ISSUE THREAD

**Issue by Procyon-b** [gregsadetsky/chrome-dont-add-custom-search-engines#18]
https://duckduckgo.com/ is automatically added.

The problem is probably with the code before "autoDetect". In either "Opensearch" or "Suggestion service".
I'll look into it.

**Comment by Procyon-b** [comment]
It seems fixed with this little modification.
I have moved code to a function "catchOpenSearch()", which is called twice now.
[content.zip](https://github.com/gregsadetsky/chrome-dont-add-custom-search-engines/files/2312206/content.zip)

**Comment by Procyon-b** [comment]
I can tell you that since I use this version of the code, no SE slipped through. But I have no idea if this breaks sites.

**Comment by gregsadetsky** [comment]
Heya, I just tested the latest (0.0.5) version and only `dontbubble.us` (related to DDG) and `redbubble.com` slipped through (against ~100 sites). Looking great! I'm going to push it now.

Thank you both as always for the stellar amazing work!

**Comment by Procyon-b** [comment]
Tested the 2 sites with the latest code (see content.zip on Aug 23 above), and it blocks those too.  :)

**Comment by cxw42** [comment]
@Procyon-b Are you comfortable enough with the GitHub workflow that you'd like to open a pull request for the 2018/08/23 content.zip code, or would you like me to do so as I did last time?

**Comment by Procyon-b** [comment]
I haven't look much at the interface here. But I know I have done it before in june. The questions I asked you some weeks ago was because I didn't want to create duplicates, or unnecessary steps.
I don't have time to do it right now (it's 19:55 here). You can if you want it done now.   ;)

**Comment by cxw42** [comment]
No worries - at your convenience :) .  Once you open the PR I'll give it a try.

**Comment by cxw42** [comment]
@gregsadetsky Re. https://github.com/gregsadetsky/chrome-dont-add-custom-search-engines/issues/18#issuecomment-424394445 - sometime when you have a chance, would you please update the [wiki page](https://github.com/gregsadetsky/chrome-dont-add-custom-search-engines/wiki/Sites-known-to-be-added-as-custom-search-engines) with your list of sites?  It sounds like you are testing far more than are currently listed, and I'd like to see what we have for #7.  Thanks!

**Comment by cxw42** [comment]
This looks good to me!  `redbubble.com` also appears to be fixed by these changes, merged in #25.  Thanks, @Procyon-b!
