### ISSUE TITLE
a couple thai sites getting through

### ISSUE THREAD

**Issue by Incog5** [gregsadetsky/chrome-dont-add-custom-search-engines#26]
https://www.advice.co.th/search?keyword=%s

https://www.homepro.co.th/homePro/th/search/?selectedView=listView&text=%s

**Comment by cxw42** [comment]
Thanks for the report!  We'll take a look.

If you are comfortable loading extensions unpacked, would you please try https://github.com/cxw42/chrome-dont-add-custom-search-engines/tree/pr20 and let us know if you see any difference?  That is the next version planned to be released.  Thank you!

**Comment by Incog5** [comment]
I loaded pr-20 version 0.0.6, but those two sites still make it through.

**Comment by cxw42** [comment]
OK- thanks for checking!

**Comment by cxw42** [comment]
Repro after merging #25 on Chrome 75.0.3770.100, regardless of whether the page has finished loading when I run the search.

**Comment by Procyon-b** [comment]
They are using an "invalid" value in the "type" attribute of the input field.
I have a fix ready in my version. Not hard to do.

**Comment by cxw42** [comment]
@Procyon-b thanks!  In a fork?  I can't see it in the network graph.  Would you please send a PR or upload the ZIP when you have a chance?  Much appreciated!

**Comment by Procyon-b** [comment]
No, sorry, not yet in my fork. Only as dev extension on my local HD.
I'll probably create 3 branches, one that fixes this bug in the current version; one that adds support to fix "dynamic" sites (the search form is created only when needed, and escapes the detection); and finally one that adds the possibility to whitelist a site for the next 90 seconds.
