### ISSUE TITLE
The Badge Text never show

### ISSUE THREAD

**Issue by snowman** [gregsadetsky/chrome-dont-add-custom-search-engines#29]
### How do those codes work?

https://github.com/gregsadetsky/chrome-dont-add-custom-search-engines/blob/e8b215c10054aa8e96a28502ec79266be19072bf/src/bg.js#L1-L10

### Description
In [content.js](https://github.com/gregsadetsky/chrome-dont-add-custom-search-engines/blob/master/src/content.js), I could not found the code `chrome.runtime.sendMessage`

#### Document
- [chrome.runtime.onMessage](https://developer.chrome.com/apps/runtime#event-onMessage)
- [chrome.runtime.sendMessage](https://developer.chrome.com/apps/runtime#method-sendMessage)

**Comment by gregsadetsky** [comment]
Great point, it's quite possible that the code to show the badge was removed at some point. It's not necessarily the most important / interesting piece of code, so it might have left without anyone really noticing..! :-)

**Comment by cxw42** [comment]
@gregsadetsky I see you have removed the text mentioning the badge from the Chrome Web Store entry --- shall we just remove that code from bg.js and move on?  The whole point of the extension is to _not_ make things appear in the UI ;) .

**Comment by gregsadetsky** [comment]
Definitely agree, the badge icon was not necessary, or useful. Good riddance! :-) Thank you!
