### ISSUE TITLE
Search results don't load on canadiantire.ca

### ISSUE THREAD

**Issue by snowbound** [gregsadetsky/chrome-dont-add-custom-search-engines#33]
I couldn't figure out why when I went to canadiantire.ca and tried to search for glue all I saw was spinning circles. Version showed 0.0.6. Noticed there was a slider in settings regarding collect errors. I went to another computer that has Brave browser installed and the 0.0.6 extension and it had no such problem.

**Comment by cxw42** [comment]
Thanks for reporting!  I'm sorry to say I cannot reproduce the issue.  When I visit http://canadiantire.ca on a desktop Chrome, it redirects me to <https://www.canadiantire.ca/en/homepage-themes/2020/D320-sourcepage-ontario-may09.html>.  I then type `glue` in the box that says "What are you looking for today?".  I hit Enter and am taken to a search-results page.  I wait for a few seconds, then get a screenful of results.  This is with v0.0.6 on Chromium 81.0.4044.138 (Official Build) snap (64-bit) on Ubuntu 18.04.2.

Would you please try again, and try with the extension disabled, and see if you still have the problem?  If so, please give us your `chrome://version` information and more details of the steps you followed that triggered the error.  Thanks very much!

**Comment by snowbound** [comment]
Brave is up to date
Version 1.9.45 Chromium: 81.0.4044.122 (Official Build) beta (64-bit)
<https://brave.com/latest/>

I noticed that this extension even though it shows its version as 0.0.6
there is a slider called "Collect Errors" whereas an install on another
system does not have that slider in the extension which is also 0.0.6

I am wondering if there is another extension that is either causing this
issue or interacting with yours. I will have to do further testing here
when I get a chance.

**Comment by cxw42** [comment]
Thanks!  The "Collect errors" status doesn't make a difference on my system, but it's always possible Chromium could be doing something strange.

Thanks in advance for the additional testing!  Extension interactions are always a possibility.

**Comment by snowbound** [comment]
Seems Bypass PayWalls extension is the culprit. Disabling that or changing
its behaviour to "On Click" rather than its default of "On all sites"
appears to have fixed the issue.

**Comment by cxw42** [comment]
Thanks for investigating further - glad you figured it out!  I think, then, that this issue can be closed.  Do you agree or not?

**Comment by snowbound** [comment]
Yes please close this ticket

**Comment by Procyon-b** [comment]
Just a clarification about "collect errors".
It's for developers. You only see it if you enable "Developer mode" on `chrome://extensions/`
It tells chrome to keep track of javascript errors on any page of that extension (background, popup, settings page if you have one, etc...). It displays an "Errors" button (next to "Details" and "Remove") when it has collected errors.
