### ISSUE TITLE
sunset extension?

### ISSUE THREAD

**Issue by gregsadetsky** [gregsadetsky/chrome-dont-add-custom-search-engines#40]
I just noticed that custom search engines now appear in the Chrome settings under "Inactive Sites"

it seems that Chrome changed its default behaviour! new custom search engines are not enabled by default! :-)

also see [this article](https://9to5google.com/2022/03/18/chrome-site-search-activate/) and [this tweet](https://twitter.com/googlechrome/status/1504858912692084745) from the Chrome team

so... is this extension still useful? :-) @cxw42 thoughts?

**Comment by dnmTX** [comment]
@gregsadetsky just to give you my 2 cents based on my observations. Yes,many search engines are not added automatically to Chrome,some are added to the Inactive Sites and one have the option to either activate them or to remain inactive and some,like in YouTube for example are like before(adding themselves autamatically). So i think your extension is still pretty much relevant 👍

**Comment by gregsadetsky** [comment]
ah, that's great! thanks for your input. I didn't know youtube (and other google sites?) got special passes, ha :-)

cheers

**Comment by cxw42** [comment]
This extension is still a beautiful thing:
![image](https://user-images.githubusercontent.com/10515894/209479939-86c7507a-8979-406d-9ba5-f220e4f720f8.png)
:+1: keep it going!
