### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'removeEventListener')

### ISSUE THREAD

**Issue by Incog5** [gregsadetsky/chrome-dont-add-custom-search-engines#41]
In the extension errors panel
chrome://extensions/?errors=keaedgeohkihipgjbbijdldkiaodgopm

getting this error:

Uncaught TypeError: Cannot read properties of undefined (reading 'removeEventListener')]

Context
https://www.youtube.com/

Stack Trace
content.js:10 (anonymous function)

// called when the user clicks an element of the form (any field or button).
// The parameter passed is the event object.
function clickApply(e) {
      if(DEBUG) console.info({'form onclick':e});
      // remove onclick. One fix only
      e.srcElement.form.removeEventListener("click", clickApply);           **<------ Line 10**
      applyFix(e.srcElement.form);
} //clickApply

**Comment by cxw42** [comment]
Is this still happening?  I am not able to repro on Chromium 113

**Comment by Incog5** [comment]
Haven't seen it in a while, closed.
