### ISSUE TITLE
License should be CC-BY-SA 3.0?

### ISSUE THREAD

**Issue by cxw42** [gregsadetsky/chrome-dont-add-custom-search-engines#5]
This was originally based on [a Stack Exchange answer](http://superuser.com/a/996781/), and the SE license is [CC-BY-SA 3.0](https://creativecommons.org/licenses/by-sa/3.0/).  Also, I don't see anything on [the original answerer's profile](https://superuser.com/users/58978/10basetom) that provides any other license.  I am not a lawyer, but as far as I know, those circumstances require this code be CC-BY-SA 3.0 as well.  Thoughts?

**Comment by gregsadetsky** [comment]
Hey, thanks for the note. I'm not a lawyer either :-) but I think that you may be correct, as the CC BY-SA 3.0 license does require to "ShareAlike" ("... you must distribute ... under the same license as the original").

Happy to change the license! I'll push that commit now.

Thank you!
